<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="18457" started-at="2016-07-20T20:07:36Z" finished-at="2016-07-20T20:07:54Z">
    <groups>
    </groups>
    <test name="FF Test" duration-ms="18457" started-at="2016-07-20T20:07:36Z" finished-at="2016-07-20T20:07:54Z">
      <class name="ExtendsReports.TestCase2">
        <test-method status="PASS" signature="setUp()[pri:0, instance:ExtendsReports.TestCase2@29ee9faa]" name="setUp" is-config="true" duration-ms="4707" started-at="2016-07-20T16:07:36Z" finished-at="2016-07-20T16:07:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="hasanBhuiyan()[pri:0, instance:ExtendsReports.TestCase2@29ee9faa]" name="hasanBhuiyan" duration-ms="26" started-at="2016-07-20T16:07:40Z" finished-at="2016-07-20T16:07:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at ExtendsReports.TestCase2.hasanBhuiyan(TestCase2.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hasanBhuiyan -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:ExtendsReports.TestCase2@29ee9faa]" name="tearDown" is-config="true" duration-ms="516" started-at="2016-07-20T16:07:41Z" finished-at="2016-07-20T16:07:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=hasanBhuiyan status=FAILURE method=TestCase2.hasanBhuiyan()[pri:0, instance:ExtendsReports.TestCase2@29ee9faa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="atEnd()[pri:0, instance:ExtendsReports.TestCase2@29ee9faa]" name="atEnd" is-config="true" duration-ms="433" started-at="2016-07-20T16:07:54Z" finished-at="2016-07-20T16:07:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- atEnd -->
      </class> <!-- ExtendsReports.TestCase2 -->
      <class name="ExtendsReports.TestCase1">
        <test-method status="PASS" signature="setUp()[pri:0, instance:ExtendsReports.TestCase1@c038203]" name="setUp" is-config="true" duration-ms="6079" started-at="2016-07-20T16:07:41Z" finished-at="2016-07-20T16:07:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="taltekcTEST()[pri:0, instance:ExtendsReports.TestCase1@c038203]" name="taltekcTEST" duration-ms="31" started-at="2016-07-20T16:07:47Z" finished-at="2016-07-20T16:07:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at ExtendsReports.TestCase1.taltekcTEST(TestCase1.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- taltekcTEST -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:ExtendsReports.TestCase1@c038203]" name="tearDown" is-config="true" duration-ms="385" started-at="2016-07-20T16:07:47Z" finished-at="2016-07-20T16:07:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=taltekcTEST status=FAILURE method=TestCase1.taltekcTEST()[pri:0, instance:ExtendsReports.TestCase1@c038203] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:ExtendsReports.TestCase1@c038203]" name="setUp" is-config="true" duration-ms="6612" started-at="2016-07-20T16:07:48Z" finished-at="2016-07-20T16:07:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:ExtendsReports.TestCase1@c038203]" name="tearDown" is-config="true" duration-ms="93" started-at="2016-07-20T16:07:54Z" finished-at="2016-07-20T16:07:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=taltekcTest2 status=SUCCESS method=TestCase1.taltekcTest2()[pri:0, instance:ExtendsReports.TestCase1@c038203] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="taltekcTest2()[pri:0, instance:ExtendsReports.TestCase1@c038203]" name="taltekcTest2" duration-ms="0" started-at="2016-07-20T16:07:54Z" finished-at="2016-07-20T16:07:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- taltekcTest2 -->
      </class> <!-- ExtendsReports.TestCase1 -->
    </test> <!-- FF Test -->
  </suite> <!-- Suite -->
</testng-results>
